version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school-api
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=ep-little-bread-a98ff49j-pooler.gwc.azure.neon.tech;Port=5432;Database=school-db;Username=neondb_owner;Password=npg_HILmMWYe07fN;SslMode=VerifyFull;TrustServerCertificate=true
